---
version: "3.8"
services:
  svc:
    build:
      context: .
    container_name: babyrecord-svc
    image: babyrecord-svc
    environment:
      - svrhost
      - dbhost=${dbinternalip}
      - dbport
      - dbusr
      - dbname
      - PGPASSWORD=${dbpwd}
    depends_on:
      postgres:
        condition: service_started
      migration:
        condition: service_completed_successfully
    ports:
      - ${svcportbinding}
    networks:
      brnet:
        ipv4_address: ${svcinternalip}
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${dbusr}
      - POSTGRES_PASSWORD=${dbpwd}
    volumes:
      - pgdatavol:/var/lib/postgresql/data
    networks:
      brnet:
        ipv4_address: ${dbinternalip}
    restart: unless-stopped

  migration:
    image: babyrecord-svc:latest
    command: psql -h ${dbinternalip} -U ${dbusr} -d ${dbname} -w -f /usr/src/app/db.sql
    environment:
      - dbhost=${dbinternalip}
      - dbusr
      - dbname
      - PGPASSWORD=${dbpwd}
    networks:
      brnet:
        ipv4_address: "10.50.0.20"
    depends_on:
      postgres:
        condition: service_started

  web:
    build:
      context: ./web
    container_name: babyrecord-web
    image: babyrecord-web
    depends_on:
      svc:
        condition: service_started
    environment:
      - webport
      - svcinternalip
      - svcport
    ports:
      - ${webportbinding}
    networks:
      brnet:
        ipv4_address: "10.50.0.12"
    restart: unless-stopped

networks:
  brnet:
    ipam:
      driver: default
      config:
        - subnet: "10.50.0.0/24"

volumes:
  pgdatavol:
