---
version: "3.8"
services:
  svc:
    build:
      context: .
    container_name: babyrecord-svc
    image: babyrecord-svc
    environment:
      - svrhost=0.0.0.0
      - dbhost=10.50.0.10
      - dbport=5432
      - dbusr
      - dbname
      - PGPASSWORD=${dbpwd}
      - jwtkey
      - userpwd
    depends_on:
      postgres:
        condition: service_started
      dbmigration:
        condition: service_completed_successfully
    ports:
      - ${svcportbinding}
    networks:
      brnet:
        ipv4_address: "10.50.0.11"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${dbusr}
      - POSTGRES_PASSWORD=${dbpwd}
    volumes:
      - pgdatavol:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    networks:
      brnet:
        ipv4_address: "10.50.0.10"
    restart: unless-stopped

  dbmigration:
    build:
      dockerfile: ./dbmigration.Dockerfile
    image: babyrecord-dbmigration
    environment:
      - dbusr
      - dbname
      - PGPASSWORD=${dbpwd}
    networks:
      brnet:
        ipv4_address: "10.50.0.20"
    depends_on:
      postgres:
        condition: service_started

  web:
    build:
      context: ./web
    container_name: babyrecord-web
    image: babyrecord-web
    depends_on:
      svc:
        condition: service_started
    environment:
      - webport=5173
      - svcinternalip=10.50.0.11
      - svcport=8080
    ports:
      - ${webportbinding}
    networks:
      brnet:
        ipv4_address: "10.50.0.12"
    restart: unless-stopped

networks:
  brnet:
    ipam:
      driver: default
      config:
        - subnet: "10.50.0.0/24"

volumes:
  pgdatavol:
